[package]
name = "foxfire"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[dependencies]
image = "0.24.2"
druid = { git = "https://github.com/linebender/druid.git", features = ["im", "svg"] }
dark-light = "0.2.2"
